name: FOSS License Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and ScanCode Toolkit
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-pip
          git clone https://github.com/nexB/scancode-toolkit.git
          cd scancode-toolkit
          ./configure

      - name: Run ScanCode on src/uuid/src
        run: |
          REPO_DIR=$(pwd)
          cd scancode-toolkit
          ./scancode --license --json-pp "$REPO_DIR/scan-output.json" "$REPO_DIR/src/uuid/src"


      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: scancode-result
          path: scan-output.json
