name: FOSS License Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ScanCode Toolkit
        run: |
          git clone https://github.com/nexB/scancode-toolkit.git
          cd scancode-toolkit
          ./configure

      - name: Run ScanCode license scan on uuid/
        run: |
          cd scancode-toolkit
          ./scancode --license --json-pp ../scan-output.json ../uuid

      - name: Check for risky licenses (exclusive or multi-licensed)
        run: |
          echo "🔍 Checking scan-output.json for risky licenses..."

          RISKY_LICENSES=("gpl-2.0" "gpl-3.0" "agpl-3.0")
          FOUND_RISKY=0
          declare -A DETECTED_LICENSES

          while IFS=$'\t' read -r path license_expr; do
            DETECTED_LICENSES["$license_expr"]=1

            for risky in "${RISKY_LICENSES[@]}"; do
              if [[ "$license_expr" == "$risky" ]]; then
                echo "::error file=$path::❗ File '$path' is exclusively under risky license: $license_expr"
                FOUND_RISKY=1
              elif [[ "$license_expr" == *"$risky"* ]]; then
                echo "::warning file=$path::⚠️ File '$path' includes risky license in multi-license expression: $license_expr"
                FOUND_RISKY=1
              fi
            done
          done < <(jq -r '.files[] | select(.license_expression != null) | [.path, .license_expression] | @tsv' scan-output.json)

          echo ""
          echo "📄 Detected License Expressions Summary:"
          for lic in "${!DETECTED_LICENSES[@]}"; do
            echo "• $lic"
          done
          echo ""

          if [ "$FOUND_RISKY" -eq 1 ]; then
            echo "::error::❌ Risky licenses detected (exclusive or multi-licensed). Failing the build."
            exit 1
          else
            echo "✅ All files are clean and safe."
          fi
